# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\simgor\Desktop\benkyo\aboutWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutWin(object):
    def setupUi(self, aboutWin):
        aboutWin.setObjectName("aboutWin")
        aboutWin.setWindowModality(QtCore.Qt.ApplicationModal)
        aboutWin.setEnabled(True)
        aboutWin.resize(497, 411)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(aboutWin.sizePolicy().hasHeightForWidth())
        aboutWin.setSizePolicy(sizePolicy)
        aboutWin.setMouseTracking(False)
        aboutWin.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        aboutWin.setStyleSheet("")
        aboutWin.setModal(True)
        self.label = QtWidgets.QLabel(aboutWin)
        self.label.setGeometry(QtCore.QRect(210, 40, 251, 50))
        font = QtGui.QFont()
        font.setFamily("文泉驿正黑")
        font.setPointSize(28)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 75 28pt \"文泉驿正黑\";\n"
"\n"
"color: rgb(85, 87, 83);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(aboutWin)
        self.label_2.setGeometry(QtCore.QRect(70, 30, 91, 109))
        self.label_2.setStyleSheet("image: url(:/img/icon.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(aboutWin)
        self.label_3.setGeometry(QtCore.QRect(40, 160, 491, 41))
        font = QtGui.QFont()
        font.setFamily("文泉驿微米黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("font: 57 13pt \"文泉驿微米黑\";\n"
"\n"
"color: rgb(85, 87, 83);")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(aboutWin)
        self.label_4.setGeometry(QtCore.QRect(240, 100, 181, 40))
        font = QtGui.QFont()
        font.setFamily("文泉驿微米黑")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("font: 57 13pt \"文泉驿微米黑\";\n"
"\n"
"color: rgb(136, 138, 133);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(aboutWin)
        self.label_5.setGeometry(QtCore.QRect(40, 210, 421, 101))
        font = QtGui.QFont()
        font.setFamily("文泉驿微米黑")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.label_5.setFont(font)
        self.label_5.setMouseTracking(True)
        self.label_5.setStyleSheet("font: 57 10.5pt \"文泉驿微米黑\";\n"
"\n"
"color: rgb(136, 138, 133);")
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(aboutWin)
        self.label_7.setGeometry(QtCore.QRect(40, 321, 121, 21))
        self.label_7.setStyleSheet("color: rgb(136, 138, 133);\n"
"font: 11pt \"文泉驿微米黑\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(aboutWin)
        self.label_8.setGeometry(QtCore.QRect(40, 341, 321, 30))
        self.label_8.setStyleSheet("color: rgb(136, 138, 133);\n"
"font: 11pt \"文泉驿微米黑\";")
        self.label_8.setOpenExternalLinks(True)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(aboutWin)
        self.label_9.setGeometry(QtCore.QRect(40, 371, 301, 30))
        self.label_9.setStyleSheet("color: rgb(136, 138, 133);\n"
"font: 10pt \"文泉驿微米黑\";")
        self.label_9.setObjectName("label_9")
        self.pushButton = QtWidgets.QPushButton(aboutWin)
        self.pushButton.setGeometry(QtCore.QRect(390, 361, 81, 31))
        self.pushButton.setStyleSheet("font: 11pt \"文泉驿微米黑\";")
        self.pushButton.setObjectName("pushButton")
        self.label_10 = QtWidgets.QLabel(aboutWin)
        self.label_10.setGeometry(QtCore.QRect(160, 320, 18, 20))
        self.label_10.setStyleSheet("color: rgb(136, 138, 133);\n"
"font: 11pt \"文泉驿微米黑\";\n"
"image: url(:/img/github.png);")
        self.label_10.setOpenExternalLinks(True)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(aboutWin)
        self.pushButton.clicked.connect(aboutWin.close)
        QtCore.QMetaObject.connectSlotsByName(aboutWin)

    def retranslateUi(self, aboutWin):
        _translate = QtCore.QCoreApplication.translate
        aboutWin.setWindowTitle(_translate("aboutWin", "Sail JP Benkyo について"))
        self.label.setText(_translate("aboutWin", "Sail JP Benkyo"))
        self.label_3.setText(_translate("aboutWin", "<html><head/><body><p>Sail JP Benkyo は日本語の音節学習ソフトウェアです。</p></body></html>"))
        self.label_4.setText(_translate("aboutWin", " Version1.0.0"))
        self.label_5.setText(_translate("aboutWin", "Sail Word Cardは、GUN GPL2.0オープンソースライセンス契約に基づいてリリースされた無料のソフトウェアです。つまり、このソフトウェアを自由に実行、コピー、配布、変更、および改善できます。このコンピュータプログラムは、著作権法および国際条約によって保護されています。ご使用の際は、現地の法令を厳守してください。"))
        self.label_7.setText(_translate("aboutWin", "<html><head/><body><p>著者：Simgor001</p></body></html>"))
        self.label_8.setText(_translate("aboutWin", "<html><head/><body><p>E-Mail：<a href=\"Simgor001@outlook.com\"><span style=\" text-decoration: underline; color:#00aaff;\">Simgor001@outlook.com</span></a></p></body></html>"))
        self.label_9.setText(_translate("aboutWin", "<html><head/><body><p>Copyright © 2021 Simgor001. All Rights Reserved. </p></body></html>"))
        self.pushButton.setText(_translate("aboutWin", "確認"))
        self.label_10.setText(_translate("aboutWin", "<html><head/><body><p><a href=\"https://github.com/Simgor001/\"><span style=\" text-decoration: underline; color:#0000ff;\"></span></a></p></body></html>"))
import img_rc
